---
name: podsync

channels:
  - conda-forge

dependencies:
  - dateparser=1.2.0
  - feedparser=6.0.11
  - python=3.12.7
  - xmltodict=0.14.2
  - pip:
      - https://github.com/hfpods4085/pods/releases/download/videogram/videogram-0.4.8.tar.gz
