---
name: Schedule

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/scheduler.yml
      - config/**
      - podsync/scheduler.py
      - podsync/refresh-opml.py
      - requirements.txt
  schedule:
    - cron: 17 * * * *

permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install python packages
        run: pip install -r requirements.txt

      - name: Refresh OPML
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gh release download audio -D audio --clobber --pattern podsync.opml
          gh release download video -D video --clobber --pattern podsync.opml
          python podsync/refresh-opml.py

      - name: Sync
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_TG_TARGET: ${{ secrets.DEFAULT_TG_TARGET }}
          VIDEOGRAM_TG_SESSION_STRING: ${{ secrets.VIDEOGRAM_TG_SESSION_STRING }}
          VIDEOGRAM_YT_LANG: ${{ secrets.VIDEOGRAM_YT_LANG }}
          RSSHUB_URL: ${{ secrets.RSSHUB_URL }}
        run: |-
          gh release download metadata -D metadata --clobber
          python podsync/scheduler.py --platform youtube --config config/youtube.json
          python podsync/scheduler.py --platform bilibili --config config/bilibili.json

      - name: Clean up old assets
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python podsync/clean-up.py

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: gautamkrishnar/keepalive-workflow@v2
